CXX=arm-angstrom-linux-gnueabi-g++
SOURCES=main.cpp part1.cpp part2.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=parts.target

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CXX) $(OBJECTS) -o $@

%.o: %.c
	$(CXX) -c $< -o $@

clean : 
	@rm -rf *o ${EXECUTABLE}

help :
	@echo all clean help $(EXECUTABLE) $(OBJECTS)